doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Astrologer:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Representation/Database/config/doctrine'
                prefix: 'App\Domain\Astrologer\Entity'
            AstrologerService:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Representation/Database/config/doctrine'
                prefix: 'App\Domain\AstrologerService\Entity'
            Service:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Representation/Database/config/doctrine'
                prefix: 'App\Domain\Service\Entity'
            User:
                is_bundle: false
                type: yml
                dir: '%kernel.project_dir%/src/Representation/Database/config/doctrine'
                prefix: 'App\Domain\User\Entity'
