version: '3.7'

services:
  postgres:
    build: docker/postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432

  webserver:
    build:
      context: docker/nginx
      target: dev
    volumes:
      - ./public:/var/www/project/public
      - ./vendor:/var/www/project/vendor:cached
      - ./docker/nginx/conf.d/development.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
    ports:
      - ${WEBSERVER_PORT}:80
      - ${WEBSERVER_PORT_SSL}:443

  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    working_dir: /var/www/project
    volumes:
      - ~/.composer:/.composer
      - ./:/var/www/project:delegated
      - ./vendor:/var/www/project/vendor:cached
      - /var/www/project/var/cache
    links:
      - postgres

networks:
  default:
    external:
      name: obrio