kernel:
    resource: ../../src/Kernel.php
    type: annotation

astrologers_controller:
    resource: ../../src/Representation/AstrologerApi/Controller
    type: annotation
    prefix: /api
    name_prefix: api_
