App\Domain\AstrologerService\Entity\AstrologerService:
  type: entity
  table: astrologer_services
  id:
    id:
      type: uuid
      generator:
        strategy: AUTO
  fields:
    astrologer:
      targetEntity: App\Domain\Astrologer\Entity\Astrologer
      nullable: false
    service:
      targetEntity: App\Domain\Service\Entity\Service
      nullable: false
    price:
      type: decimal
      precision: 12
      scale: 2
      nullable: false
